Fix typo on Contributing
meilisearch/firestore-meilisearch pull request #54
Opened 2022-03-29 10:06 UTC by alallema

2022-03-29 10:19 UTC, curquiza reviewed
Regarding the CONTRIBUTING improvement (maybe not in this PR)
- `After which don't forget to rebuild the project.` -> why?
- `The version.sh script will add and commit the modification but you till need to verify it and push it.` -> "modifications", "still" + which modifications? to every file?
- `be sure you apply [these recommandations]` -> recommendation
- Maybe we could add information about what kind of CI (publish to npm) you trigger when creating a GitHub release, like [here](https://github.com/meilisearch/meilisearch-js/blob/main/CONTRIBUTING.md#how-to-publish-the-release) "GitHub Actions will be triggered and push the package to [npm](https://www.npmjs.com/package/meilisearch)."

2022-03-29 10:21 UTC, curquiza commented
Also, in the CONTRIBUTING, maybe you should start by publishing to NPM and then to firebase. If there is any failure in the CI, it will prevent you pushing a wrong to firebase

2022-03-29 13:26 UTC, brunoocasali requested changes
Hey, I have some suggestions :)

2022-03-29 13:26 UTC, brunoocasali commented on CONTRIBUTING.md
> +After which, don't forget to rebuild the project to check if any changes has been forgotten on the `js` files in the `functions/lib` directory.
```suggestion
After which, don't forget to rebuild the project to check if any changes have been overlooked on the `js` files in the `functions/lib` directory.
```

2022-03-29 13:29 UTC, curquiza reviewed
Almost good to me, well done ;)
Don't wait for my approval to merge!

Also, by curiosity, why did you remove the `commit` par from the script?

2022-03-29 13:29 UTC, curquiza commented on CONTRIBUTING.md
> +```
```suggestion
```bash
```

2022-03-29 14:03 UTC, mdubus approved these changes
LGTM 🔥

2022-03-29 14:29 UTC, brunoocasali approved these changes
🔥 🔥

2022-03-29 14:36 UTC, alallema commented
bors merge

2022-03-29 14:38 UTC, merged

2022-03-29 14:42 UTC, alallema commented
> Also, by curiosity, why did you remove the commit par from the script?

@curquiza 
Sorry I totally forgot to answer this. I remove it because when the script commits you can not see the modification of the files there are already committed. I find it not intuitive at all because you don't know what has changed and what are committed. So it's cool but too unclear finally.

2022-03-30 07:45 UTC, alallema commented
> By doing `git status` you will see the committed files, and also you can check the diff of the current committed changes by doing `git diff --staged`, but you're right, it's a less known command 😉

You will only see the file added with `git status` and not the ones that have been committed same for the `git diff --staged`